<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260524100332 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ingredient_entity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E25284295E237E06 ON ingredient_entity (name)');
        $this->addSql('CREATE TABLE recipes_entity (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE recipes_entity_ingredient_entity (recipes_entity_id INT NOT NULL, ingredient_entity_id INT NOT NULL, PRIMARY KEY (recipes_entity_id, ingredient_entity_id))');
        $this->addSql('CREATE INDEX IDX_75180869414733 ON recipes_entity_ingredient_entity (recipes_entity_id)');
        $this->addSql('CREATE INDEX IDX_75180868B57D52A ON recipes_entity_ingredient_entity (ingredient_entity_id)');
        $this->addSql('ALTER TABLE recipes_entity_ingredient_entity ADD CONSTRAINT FK_75180869414733 FOREIGN KEY (recipes_entity_id) REFERENCES recipes_entity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE recipes_entity_ingredient_entity ADD CONSTRAINT FK_75180868B57D52A FOREIGN KEY (ingredient_entity_id) REFERENCES ingredient_entity (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE recipes_entity_ingredient_entity DROP CONSTRAINT FK_75180869414733');
        $this->addSql('ALTER TABLE recipes_entity_ingredient_entity DROP CONSTRAINT FK_75180868B57D52A');
        $this->addSql('DROP TABLE ingredient_entity');
        $this->addSql('DROP TABLE recipes_entity');
        $this->addSql('DROP TABLE recipes_entity_ingredient_entity');
    }
}
